openapi: 3.0.3
info:
  title: GameBanana APIs (Unofficial Documentation)
  version: 0.1.0
  description: A simple API reference made by ImMalloy. You can use this however you
    like.
servers:
- url: https://gamebanana.com
  description: GameBanana main host
- url: https://api.gamebanana.com
  description: GameBanana API host
- url: https://dev.gamebanana.com
  description: GameBanana development host
- url: https://api.dev.gamebanana.com
  description: GameBanana development API host
